package org.sdm.core.maven;

class ModuleMetadata2 {
    
    Map resolveMap = [
    	'org.springframework.aop.scope': [ [group: 'org.springframework', module: 'spring-aop'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.aop.support': [ [group: 'org.springframework', module: 'spring-aop'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.aop.support.annotation': [ [group: 'org.springframework', module: 'spring-aop'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.aop.target': [ [group: 'org.springframework', module: 'spring-aop'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.aop.target.dynamic': [ [group: 'org.springframework', module: 'spring-aop'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.annotation': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.access': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.access.el': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.annotation': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.config': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.generic': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.parsing': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.serviceloader': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.support': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.wiring': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.factory.xml': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.propertyeditors': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.beans.support': [ [group: 'org.springframework', module: 'spring-beans'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.cache.ehcache': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.access': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.annotation': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.config': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.event': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.i18n': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.context.weaving': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ejb.access': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ejb.config': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ejb.interceptor': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ejb.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument.classloading': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument.classloading.glassfish': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument.classloading.oc4j': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument.classloading.tomcat': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument.classloading.weblogic': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.core': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.core.metadata': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.core.namedparam': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.core.simple': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.core.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.datasource': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.datasource.lookup': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.object': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support.incrementer': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support.lob': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support.nativejdbc': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support.rowset': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jdbc.support.xml': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.config': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.connection': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.core': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.core.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.listener': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.listener.adapter': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.listener.endpoint': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.listener.serversession': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.remoting': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.support.converter': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jms.support.destination': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.access': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export.annotation': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export.assembler': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export.metadata': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export.naming': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.export.notification': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jmx.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jndi': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.jndi.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.mail': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.mail.javamail': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.hibernate3': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.hibernate3.annotation': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.hibernate3.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.ibatis': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.ibatis.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jdo': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jdo.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jpa': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jpa.persistenceunit': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jpa.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.jpa.vendor': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.toplink': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.orm.toplink.support': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.remoting': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.remoting.rmi': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.remoting.soap': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.remoting.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.backportconcurrent': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.commonj': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.concurrent': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.quartz': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scheduling.timer': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting.bsh': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting.config': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting.groovy': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting.jruby': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.scripting.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.stereotype': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui.context': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui.context.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui.freemarker': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui.jasperreports': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.ui.velocity': [ [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.validation': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.validation.support': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'org.springframework.instrument': [ [group: 'org.springframework', module: 'spring-context'], [group: 'org.springframework', module: 'spring'] ],
	'grails.spring': [ [group: 'org.grails', module: 'grails-spring'] ],
	'org.codehaus.groovy.grails.commons.spring': [ [group: 'org.grails', module: 'grails-spring'] ],
	'org.apache.commons.collections.bag': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.bidimap': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.buffer': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.collection': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.comparators': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.functors': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.iterators': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.keyvalue': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.list': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.map': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'org.apache.commons.collections.set': [ [group: 'commons-collections', module: 'commons-collections'] ],
	'junit.awtui': [ [group: 'junit', module: 'junit'] ],
	'junit.extensions': [ [group: 'junit', module: 'junit'] ],
	'junit.framework': [ [group: 'junit', module: 'junit'] ],
	'junit.runner': [ [group: 'junit', module: 'junit'] ],
	'junit.swingui': [ [group: 'junit', module: 'junit'] ],
	'junit.textui': [ [group: 'junit', module: 'junit'] ],
	'org.junit': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.requests': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.runners': [ [group: 'junit', module: 'junit'] ],
	'org.junit.runner': [ [group: 'junit', module: 'junit'] ],
	'org.junit.runner.manipulation': [ [group: 'junit', module: 'junit'] ],
	'org.junit.runner.notification': [ [group: 'junit', module: 'junit'] ],
	'org.junit.runners': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.builders': [ [group: 'junit', module: 'junit'] ],
	'org.junit.runners.model': [ [group: 'junit', module: 'junit'] ],
	'org.hamcrest': [ [group: 'junit', module: 'junit'] ],
	'org.hamcrest.core': [ [group: 'junit', module: 'junit'] ],
	'org.hamcrest.internal': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.categories': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.max': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.results': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.runners': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.theories': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.theories.internal': [ [group: 'junit', module: 'junit'] ],
	'org.junit.experimental.theories.suppliers': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.matchers': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.runners.model': [ [group: 'junit', module: 'junit'] ],
	'org.junit.internal.runners.statements': [ [group: 'junit', module: 'junit'] ],
	'org.junit.matchers': [ [group: 'junit', module: 'junit'] ],
	'org.junit.rules': [ [group: 'junit', module: 'junit'] ],
	'org.apache.commons.io.comparator': [ [group: 'commons-io', module: 'commons-io'] ],
	'org.apache.commons.io': [ [group: 'commons-io', module: 'commons-io'] ],
	'org.apache.commons.io.filefilter': [ [group: 'commons-io', module: 'commons-io'] ],
	'org.apache.commons.io.input': [ [group: 'commons-io', module: 'commons-io'] ],
	'org.apache.commons.io.output': [ [group: 'commons-io', module: 'commons-io'] ],
	'jline': [ [group: 'jline', module: 'jline'] ],
	'org.jaxen': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.dom': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.dom4j': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.expr': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.expr.iter': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.function': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.function.ext': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.function.xslt': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.javabean': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.jdom': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.pattern': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.saxpath': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.saxpath.base': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.saxpath.helpers': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.util': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.jaxen.xom': [ [group: 'jaxen', module: 'jaxen'] ],
	'org.apache.commons.digester.parser': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'org.apache.commons.digester': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'org.apache.commons.digester.plugins.strategies': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'org.apache.commons.digester.plugins': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'org.apache.commons.digester.xmlrules': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'org.apache.commons.digester.substitution': [ [group: 'commons-digester', module: 'commons-digester'] ],
	'com.sun.activation.registries': [ [group: 'javax.activation', module: 'activation'] ],
	'com.sun.activation.viewers': [ [group: 'javax.activation', module: 'activation'] ],
	'javax.ws.rs': [ [group: 'javax.ws.rs', module: 'jsr311-api'] ],
	'javax.ws.rs.core': [ [group: 'javax.ws.rs', module: 'jsr311-api'] ],
	'javax.ws.rs.ext': [ [group: 'javax.ws.rs', module: 'jsr311-api'] ],
	'javax.xml.bind': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.bind.annotation': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.bind.annotation.adapters': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.bind.attachment': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.bind.helpers': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.bind.util': [ [group: 'javax.xml.bind', module: 'jaxb-api'] ],
	'javax.xml.soap': [ [group: 'javax.xml.soap', module: 'saaj-api'] ],
    ]
}